var defaultWords = [
    "school,2,places",
    "pillow,1,in-the-house",
    "titanic,3,movies",
    "disney,2,places",
    "birds,2,nature",
    "tree,1,places",
    "flower,1,nature",
    "clouds,1,nature",
    "tarzan,4,fictional",
    "mickey mouse,1,fictional",
    "calvin and hobbes,5,fictional",
    "computer,1,technology",
    "bed,1,in-the-house",
    "minecraft,3,games",
    "dictionary,6,tools",
    "table,1,in-the-house",
    "internet,3,technology",
    "japan,3,places",
    "fish,1,nature",
    "bear,2,nature",
    "tiger,3,nature",
    "cheetah,4,nature",
    "dog,2,nature",
    "cat,2,nature",
    "grass,1,nature",
    "new york,3,places",
    "golden gate bridge,4,places",
    "saturn,1,places",
    "earth,2,places",
    "sun,1,places",
    "moon,2,places",
    "ipad,3,technology",
    "potato chips,3,food",
    "snacks,4,food",
    "ants,2,nature",
    "cockroach,3,nature",
    "shaving,4,activities",
    "door,1,in-the-house",
    "window,1,in-the-house",
    "nuts,3,food",
    "candy,2,food",
    "lightbulb,1,technology",
    "camera,1,technology",
    "phone,1,technology",
    "lantern,2,technology",
    "lamp,1,technology",
    "china,3,places",
    "apple,1,food",
    "banana,1,food",
    "strawberry,1,food",
    "pinecone,2,nature",
    "rubix cube,2,games",
    "bird,1,nature",
    "birdhouse,2,places",
    "soul,3,misc",
    "sword,1,weapons",
    "youtube,1,technology",
    "swimming,2,sports",
    "origami,4,arts",
    "wood,2,misc",
    "guitar,2,arts",
    "piano,2,arts",
    "duck,3,nature",
    "painting,3,arts",
    "chair,1,in-the-house",
    "house,1,in-the-house",
    "computer,1,technology",
    "australia,2,places",
    "bacon,2,food",
    "tennis,2,sports",
    "drone,3,technology",
    "couch,2,in-the-house",
    "football,2,sports",
    "cracker barrel,2,places",
    "bread,2,food",
    "poop,2,funny",
    "safari,5,activities",
    "notebook,2,tools",
    "car,2,transportation",
    "orlando,3,places",
    "neighbor,3,people",
    "plant,2,nature",
    "dove,4,nature",
    "church,3,places",
    "valentines day,4,holidays",
    "christmas,4,holidays",
    "pen,1,tools",
    "pencil,1,tools",
    "sketch book,1,arts",
    "time,2,misc",
    "teacher,2,occupation",
    "destroy,4,misc",
    "star wars,2,movies",
    "its a small world,4,places",
    "doll,3,toys",
    "squirell,3,nature",
    "lobster,2,nature",
    "lead pencil,2,tools",
    "aladin,3,fictional",
    "xbox,2,games",
    "sun burn,3,ailments",
    "corona virus,3,ailments",
    "nurse,4,occupations",
    "doctor,4,occupations",
    "fireman,4,occupations",
    "police officer,3,occupations",
    "pilot,4,occupations",
    "space,2,places",
    "astronaut,3,occupations",
    "projector,3,technology",
    "movie theater,3,places",
    "road,2,transportation",
    "swing,2,activities",
    "spray paint,2,tools",
    "orange,3,food",
    "eyebrow,1,anatomy",
    "mouth,1,anatomy",
    "buttocks,2,anatomy",
    "hand,2,anatomy",
    "leg,2,anatomy",
    "hair,2,anatomy",
    "curtain,2,in-the-house",
    "wheel,2,tools",
    "whale,2,nature",
    "dolphin,2,nature",
    "donut,1,food",
    "kettle,3,in-the-house",
    "tea,3,food",
    "mexico,2,places",
    "french bread,2,food",
    "picnic,3,activities",
    "toothbrush,2,tools",
    "dragon,4,fictional",
    "peach,3,food",
    "tomato,3,food",
    "pepperoni pizza,2,food",
    "burger,2,food",
    "french fries,2,food",
    "truck,2,transportation",
    "ping pong,3,sports",
    "basketball,3,sports",
    "soccer,3,sports",
    "baseball,2,sports",
    "cap,2,clothes",
    "cup,1,in-the-house",
    "pinguin,3,nature",
    "screw driver,2,tools",
    "wrench,2,tools",
    "eraser,2,tools",
    "rocket,1,transportation",
    "running,3,sports",
    "fan,2,tools",
    "frisbee,2,toys",
    "vase,2,in-the-house",
    "drinking,2,activities",
    "zeus,4,fictional",
    "hercules,5,fictional",
    "mulan,4,movies",
    "skyscraper,3,buildings",
    "engineer,4,occupation",
    "pipe dream,3,expressions",
    "punk rock,3,arts",
    "hip hop,4,arts",
    "turn table,3,arts",
    "motorcycle,3,transportation",
    "keyboard,2,arts",
    "glasses,2,tools",
    "heart break,3,expressions",
    "earth quake,3,disasters",
    "spiderman,2,movies",
    "godzilla,3,movies",
    "jeopordy,4,television",
    "wheel of fortune,3,television",
    "brickhouse,3,expressions",
    "winnie the pooh,3,television",
    "missle,2,weapons",
    "battle ship,2,weapons",
    "skateboard,2,sports",
    "snow boarding,3,sports",
    "birthday cake,2,food",
    "neck beard,3,expressions",
    "holy cow,3,expressions",
    "bart simpson,1,fictional",
    "william shakespeare,6,people",
    "monster truck,2,transportation",
    "Iron Man,3,movies",
    "Macaroni,2,food",
    "flood,3,disasters",
    "sneeze,3,ailments",
    "cough,3,ailments",
    "balding,4,ailments",
    "bald eagle,2,nature",
    "drums,3,arts",
    "orchestra,4,arts",
    "saxaphone,4,arts",
    "sneakers,2,clothes",
    "stinky feet,2,ailments",
    "cheese,2,food",
    "blister,3,ailments",
    "facebook,3,activities",
    "spaghetti,2,food",
    "chemist,3,occupation",
    "Tyranosaurus Rex,3,nature",
    "centipede,3,nature",
    "human centipede,3,movies",
    "clone,4,science",
    "aliens,2,nature",
    "ufo,1,occupation",
    "farmer,3,occupation",
    "farm,3,places",
    "baby,2,nature",
    "robot,2,technology",
    "drunk,3,verb",
    "washing dishes,3,activities",
    "mirror,1,in-the-house",
    "game of thrones,3,television",
    "julius ceasar,4,people",
    "rome,3,places",
    "the fast and the furious,3,movies",
    "moby dick,3,fictional",
    "out of the box,3,expressions",
    "chicken head,2,expressions",
    "tupac,4,people",
    "james bond,4,movies",
    "clueless,5,movies",
    "boys in the hood,5,movies",
    "marshmallow,2,food",
    "campire,3,activities",
    "camping,3,activities",
    "rainbow,1,nature",
    "cleopatra,4,people",
    "george washington,3,people",
    "thor,2,movies",
    "cowboy,2,occupation",
    "cruise ship,2,transportation",
    "satellite,2,technology",
    "puerto rico,4,place",
    "rage against the machine,4,arts",
    "elmo,3,fictional",
    "sesame street,4,television",
    "europe,4,place",
    "paris,3,place",
    "london,4,place",
    "antarctica,3,place",
    "USA,2,place",
    "africa,2,place",
    "india,3,place",
    "philippines,3,place",
    "brazil,3,place",
    "russia,4,place",
    "los angeles,2,place",
    "san francisco,3,place",
    "train,3,transportation",
    "bicycle,3,transportation",
    "paper airplane,2,toys",
    "yoyo,4,toys",
    "tricycle,4,toys",
    "clown,3,occupation",
    "hula hoop,2,toys",
    "eggplant,2,food",
    "austin powers,2,movies",
    "avengers,4,movies",
    "batman,4,movies",
    "herbie: the love bug,5,movies",
    "bruce less,4,people",
    "television,1,television",
    "forest,2,nature",
    "boulder,2,nature",
    "mountains,1,nature",
    "socks,4,clothes",
    "shirt,1,clothes",
    "pants,1,clothes",
    "skirt,1,clothes",
    "necktie,1,clothes",
    "high heels,2,clothes",
    "blouse,2,clothes",
    "underwear,2,clothes",
    "stove,2,in-the-house",
    "owl,4,nature",
    "polar bear,3,nature",
    "wolf,3,nature",
    "iguana,4,nature",
    "parrot,3,nature",
    "eskimo,3,people",
    "igloo,4,place",
    "colorado,2,place",
    "broken,4,misc",
    "tank,4,transportation",
    "fighter jet,4,transportation",
    "mango,3,food",
    "taco,2,food",
    "watermelon,2,food",
    "sushi,2,food",
    "cleaning,4,verb",
    "cooking,4,verb",
    "driver,4,occupation",
    "picking nose,3,activities",
    "scratching butt,3,activities",
    "biting nails,4,activities",
    "restuarant,3,place",
    "water park,4,place",
    "roller coaster,3,entertainment",
    "gold,2,nature",
    "valley,2,nature",
    "hurricane,2,disasters",
    "landslide,3,disasters",
    "firestorm,4,disasters",
    "asteriod impact,4,disasters",
    "empire state building,3,buildings",
    "burj khalifa,3,buildings",
    "eifel tower,3,buildings",
    "tokyo tower,4,buildings",
    "the great pyramid,4,buildings",
    "astronomy,6,science",
    "geology,6,science",
    "water slide,3,entertainment",
    "bumper cars,3,entertainment",
    "fun house,4,entertainment",
    "ferris wheel,2,entertainment",
    "screaming,3,verb",
    "dreaming,3,verb",
    "complaining,4,verb",
    "smiling,1,verb",
    "dancing,2,verb",
    "phyics,6,science",
    "exploring,6,science",
    "experimenting,6,science",
    "chess,3,games",
    "checkers,3,games",
    "shoots and ladders,3,games",
    "monopoly,3,games",
    "tit for tat,4,expressions",
    "stealing candy from a baby,4,expressions",
    "don't rock the boat,3,expressions",
    "give me a break,5,expressions",
    "cleaned his clock,4,expressions",
    "president's day,3,holidays",
    "thanksgiving,3,holidays",
    "halloween,2,holidays",
    "toe nail,2,anatomy",
    "guts,2,anatomy",
    "nose hair,3,anatomy",
    "ear wax,3,anatomy",
    "teeth,1,anatomy",
    "tongue,2,anatomy",
    "spine,3,anatomy",
    "liver,3,anatomy",
    "new year's day,3,holidays"



    //"WORD,SCORE,CATEGORY" NO SPACES
    //"EXAMPLE,99,THE-CATEGORY",
]